MohmmandMarble/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('admin/', admin.site.urls),

    path('', include('marble.urls')),

    path('account/', include('account.urls')),

    path('admin/', include('customadmin.urls')),
]
urlpatterns += static (settings.MEDIA_URL,  document_root = settings.MEDIA_ROOT)

marble/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('product_category/', views.product_category, name='product_category'),

    path('about_us/', views.about_us, name='about_us'),

    path('faq/', views.faq, name='faq'),

    path('contact_us/', views.contact_us, name='contact_us'),

    path('single_product/<str:pk>/', views.single_product, name='single_product'),

    path('product_mid_category/<str:pk>/', views.product_mid_category, name='product_mid_category'),

    path('product_end_category/<str:pk>/', views.product_end_category, name='product_end_category'),

    path('search_product_category/<str:pk>/', views.search_product_category, name='search_product_category'),

    path('filter_mid_category/<str:mid_category_id>/', views.filter_mid_category, name='filter_mid_category'),

    path('filter_end_category/<str:end_category_id>/', views.filter_end_category, name='filter_end_category'),
    
    path('search_product/', views.search_product, name='search_product'),
]

customadmin/models.py
from django.db import models

# Create your models here.

class add_top_category(models.Model):
    top_category_name = models.CharField(max_length=120)
    show_top_menu = models.BooleanField(default=True)

    def __str__(self):
        return self.top_category_name
    
    class Meta:
        verbose_name_plural = "1 - Add Top Category"

class add_mid_category(models.Model):
    select_top_category = models.ForeignKey(add_top_category, on_delete = models.CASCADE)
    mid_category_name = models.CharField(max_length=120)
    show_mid_menu = models.BooleanField(default=True)

    def __str__(self):
        return self.mid_category_name 

    class Meta:
        verbose_name_plural = "2 - Add Mid Category"

class add_end_category(models.Model):
    select_top_category = models.ForeignKey(add_top_category, on_delete=models.CASCADE, null=True, blank=True)
    select_mid_category = models.ForeignKey(add_mid_category, on_delete = models.CASCADE)
    end_category_name = models.CharField(max_length=120)
    show_end_menu = models.BooleanField(default=True)

    def __str__(self):
        return self.end_category_name

    class Meta:
        verbose_name_plural = "3 - Add End Category"

class add_size(models.Model):
    size_name = models.CharField(max_length=100)

    def __str__(self):
        return self.size_name
    
    class Meta:
        verbose_name_plural = "4 - Add Size"

class add_color(models.Model):
    color_name = models.CharField(max_length=100)

    def __str__(self):
        return self.color_name

    class Meta:
        verbose_name_plural = "5 - Add Color"

class add_country(models.Model):
    country_name = models.CharField(max_length=100)

    def __str__(self):
        return self.country_name

    class Meta:
        verbose_name_plural = "6 - Add Country"

class add_product(models.Model):
    select_top_category = models.ForeignKey(add_top_category, on_delete = models.CASCADE)
    select_mid_category = models.ForeignKey(add_mid_category, on_delete = models.CASCADE)
    select_end_category = models.ForeignKey(add_end_category, on_delete = models.CASCADE)
    product_name = models.CharField(max_length=120)
    old_price = models.IntegerField(null=True, blank=True)
    current_price = models.IntegerField()
    quantity = models.IntegerField()
    select_size = models.ManyToManyField(add_size, blank=True)
    select_color = models.ManyToManyField(add_color, blank=True)
    featured_photo = models.ImageField(upload_to="Media/Product_Images/Featured_image")
    photo_1 = models.ImageField(upload_to="Media/Product_Images/Other_Images", null=True, blank=True)
    photo_2= models.ImageField(upload_to="Media/Product_Images/Other_Images", null=True, blank=True)
    photo_3 = models.ImageField(upload_to="Media/Product_Images/Other_Images", null=True, blank=True)
    photo_4 = models.ImageField(upload_to="Media/Product_Images/Other_Images", null=True, blank=True)
    description = models.TextField()
    short_description = models.TextField()
    featured_desc = models.TextField()
    condition_desc = models.TextField()
    return_policy_desc = models.TextField()
    is_featured = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    status = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return self.select_top_category.top_category_name + " --- " + self.select_mid_category.mid_category_name + " --- " + self.select_end_category.end_category_name + " --- " + self.product_name

    class Meta:
        verbose_name_plural = "7 - Add Product"

class add_social_media_links(models.Model):
    facebook = models.CharField(max_length=10000, null=True, blank=True)
    twitter = models.CharField(max_length=10000, null=True, blank=True)
    youtube = models.CharField(max_length=10000, null=True, blank=True)
    watsapp = models.CharField(max_length=10000, null=True, blank=True)

class add_logo(models.Model):
    upload_logo = models.ImageField(upload_to='Media/website_images/')

class add_favicon(models.Model):
    upload_favicon = models.ImageField(upload_to="Media/website_images/")

class add_footer_contact(models.Model):
    footer_copyright = models.CharField(max_length=1000, null=True, blank=True)
    contact_address = models.TextField(null=True, blank=True)
    contact_email = models.EmailField(null=True, blank=True)
    contact_no = models.CharField(max_length=100, null=True, blank=True)
    map_iframe = models.TextField(null=True, blank=True)
    status = models.BooleanField(default=True)
    
class add_slider(models.Model):
    image = models.ImageField(upload_to="Media/website_images/slider")
    heading = models.CharField(max_length=1000, null=True, blank=True)
    content = models.CharField(max_length=2000, null=True, blank=True)
    button_text = models.CharField(max_length=100, null=True, blank=True)
    button_url = models.CharField(max_length=1000, null=True, blank=True)
    status = models.BooleanField()
    
    def __str__(self):
        return self.heading
    
class user_messages(models.Model):
    user_name = models.CharField(max_length=120, null=True, blank=True)
    email = models.CharField(max_length=120, null=True, blank=True)
    phone_no = models.CharField(max_length=120, null=True, blank=True)
    message = models.CharField(max_length=120, null=True, blank=True)
    
    def __str__(self):
        return self.user_name
    

templates/end_category_products.html
{% extends 'basic/basic.html' %}

{% load static %}

{% block content %}

    {% include 'basic/top_navbar.html' %}

    {% include 'basic/center_navbar.html' %}

    {% include 'basic/main_navbar.html' %}

    <div class="page-banner" style="background-image: url({% static 'assets/uploads/banner_product_category.jpg' %})">
        <div class="inner">
            <h1>Category: Marbles </h1>
        </div>
    </div>

    <div class="page">
        <div class="container">
            <div class="row">
                <div class="col-md-3">

                    <h3>Categories</h3>
                    <div id="left" class="span3">
                        <ul id="menu-group-1" class="nav menu">
                            {% for top_category in top_categories %}
                            {% if top_category.show_top_menu %}
                            <li class="cat-level-1 deeper parent">
                                <a class="" href="{% url 'search_product_category' top_category.id %}">
                                    <span data-toggle="collapse" data-parent="#menu-group-1" href="#cat-lvl1-id-{{ forloop.counter }}"
                                        class="sign"><i class="fa fa-plus"></i></span>
                                    <span class="lbl">{{ top_category.top_category_name }}</span>
                                </a>
                                <ul class="children nav-child unstyled small collapse" id="cat-lvl1-id-{{ forloop.counter }}">
                                    {% for mid_category in top_category.add_mid_category_set.all %}
                                    {% if mid_category.show_mid_menu %}
                                    <li class="deeper parent">
                                        <a class="" href="{% url 'filter_mid_category' mid_category.id %}">
                                            <span data-toggle="collapse" data-parent="#menu-group-1"
                                                href="#cat-lvl2-id-{{ forloop.parentloop.counter }}{{ forloop.counter }}" class="sign"><i class="fa fa-plus"></i></span>
                                            <span class="lbl lbl1">{{ mid_category.mid_category_name }}</span>
                                        </a>
                                        <ul class="children nav-child unstyled small collapse" id="cat-lvl2-id-{{ forloop.parentloop.counter }}{{ forloop.counter }}">
                                            {% for end_category in mid_category.add_end_category_set.all %}
                                            {% if end_category.show_end_menu %}
                                            <li class="item-111">
                                                <a class="" href="{% url 'filter_end_category' end_category.id %}">
                                                    <span class="sign"></span>
                                                    <span class="lbl lbl1">{{ end_category.end_category_name }}</span>
                                                </a>
                                            </li>
                                            {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                    
                </div>
                <div class="col-md-9">

                    <h3>All Products Under "Marbles"</h3>
                    <div class="product product-cat">

                        <div class="row">
                            {% if products %}
                            {% for i in products %}
                            <div class="col-md-4 item item-product-cat">
                                <div class="inner">
                                    <div class="thumb">
                                        <a href="{% url 'single_product' i.id %}">
                                        <div class="photo"
                                            style="background-image:url({{i.featured_photo.url}});">
                                        </div>
                                        </a>
                                        <div class=""></div>
                                    </div>
                                    <div class="text">
                                        <h3><a href="{% url 'single_product' i.id %}">{{i.product_name}}</a></h3>
                                        <h4>
                                            SQ.FT - <span style="color: green; font-weight: bold; font-size: 25px;"> {{i.current_price}} </span> Rs
                                        </h4>
                                        <div class="rating">
                                        </div>
                                        <p><a href="{% url 'single_product' i.id %}"><i class="fa fa-shopping-cart"></i> Add to
                                                Cart</a></p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            {% else %}
                                <p class="alert alert-danger">Sorry no record found</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'basic/footer.html' %}

    {% endblock %}

templates/filter_mid_category.html
{% extends 'basic/basic.html' %}

{% load static %}

{% block content %}

    {% include 'basic/top_navbar.html' %}

    {% include 'basic/center_navbar.html' %}

    {% include 'basic/main_navbar.html' %}

    <div class="page-banner" style="background-image: url({% static 'assets/uploads/banner_product_category.jpg' %})">
        <div class="inner">
            <h1>Category: Marbles </h1>
        </div>
    </div>

    <div class="page">
        <div class="container">
            <div class="row">
                <div class="col-md-3">

                    <h3>Categories</h3>
                    <div id="left" class="span3">
                        <ul id="menu-group-1" class="nav menu">
                            {% for top_category in top_categories %}
                            {% if top_category.show_top_menu %}
                            <li class="cat-level-1 deeper parent">
                                <a class="" href="{% url 'search_product_category' top_category.id %}">
                                    <span data-toggle="collapse" data-parent="#menu-group-1" href="#cat-lvl1-id-{{ forloop.counter }}"
                                        class="sign"><i class="fa fa-plus"></i></span>
                                    <span class="lbl">{{ top_category.top_category_name }}</span>
                                </a>
                                <ul class="children nav-child unstyled small collapse" id="cat-lvl1-id-{{ forloop.counter }}">
                                    {% for mid_category in top_category.add_mid_category_set.all %}
                                    {% if mid_category.show_mid_menu %}
                                    <li class="deeper parent">
                                        <a class="" href="{% url 'filter_mid_category' mid_category.id %}">
                                            <span data-toggle="collapse" data-parent="#menu-group-1"
                                                href="#cat-lvl2-id-{{ forloop.parentloop.counter }}{{ forloop.counter }}" class="sign"><i class="fa fa-plus"></i></span>
                                            <span class="lbl lbl1">{{ mid_category.mid_category_name }}</span>
                                        </a>
                                        <ul class="children nav-child unstyled small collapse" id="cat-lvl2-id-{{ forloop.parentloop.counter }}{{ forloop.counter }}">
                                            {% for end_category in mid_category.add_end_category_set.all %}
                                            {% if end_category.show_end_menu %}
                                            <li class="item-111">
                                                <a class="" href="{% url 'filter_end_category' end_category.id %}">
                                                    <span class="sign"></span>
                                                    <span class="lbl lbl1">{{ end_category.end_category_name }}</span>
                                                </a>
                                            </li>
                                            {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                    
                </div>
                <div class="col-md-9">

                    <h3>All Products Under "Marbles"</h3>
                    <div class="product product-cat">

                        <div class="row">
                            {% if products %}
                            {% for i in products %}
                            <div class="col-md-4 item item-product-cat">
                                <div class="inner">
                                    <div class="thumb">
                                        <a href="{% url 'single_product' i.id %}">
                                        <div class="photo"
                                            style="background-image:url({{i.featured_photo.url}});">
                                        </div>
                                        </a>
                                        <div class=""></div>
                                    </div>
                                    <div class="text">
                                        <h3><a href="{% url 'single_product' i.id %}">{{i.product_name}}</a></h3>
                                        <h4>
                                            SQ.FT - <span style="color: green; font-weight: bold; font-size: 25px;"> {{i.current_price}} </span> Rs
                                        </h4>
                                        <div class="rating">
                                        </div>
                                        <p><a href="{% url 'single_product' i.id %}"><i class="fa fa-shopping-cart"></i> Add to
                                                Cart</a></p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            {% else %}
                                <p class="alert alert-danger">Sorry no record found</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'basic/footer.html' %}

    {% endblock %}

templates/product_category.html
{% extends 'basic/basic.html' %}

{% load static %}

{% block content %}

    {% include 'basic/top_navbar.html' %}

    {% include 'basic/center_navbar.html' %}

    {% include 'basic/main_navbar.html' %}

    <div class="page-banner" style="background-image: url({% static 'assets/uploads/banner_product_category.jpg' %})">
        <div class="inner">
            <h1>Category: Marbles </h1>
        </div>
    </div>

    <div class="page">
        <div class="container">
            <div class="row">
                <div class="col-md-3">

                    <h3>Categories</h3>
                    <div id="left" class="span3">
                        <ul id="menu-group-1" class="nav menu">
                            {% for top_category in top_categories %}
                            {% if top_category.show_top_menu %}
                            <li class="cat-level-1 deeper parent">
                                <a class="" href="{% url 'search_product_category' top_category.id %}">
                                    <span data-toggle="collapse" data-parent="#menu-group-1" href="#cat-lvl1-id-{{ forloop.counter }}"
                                        class="sign"><i class="fa fa-plus"></i></span>
                                    <span class="lbl">{{ top_category.top_category_name }}</span>
                                </a>
                                <ul class="children nav-child unstyled small collapse" id="cat-lvl1-id-{{ forloop.counter }}">
                                    {% for mid_category in top_category.add_mid_category_set.all %}
                                    {% if mid_category.show_mid_menu %}
                                    <li class="deeper parent">
                                        <a class="" href="{% url 'filter_mid_category' mid_category.id %}">
                                            <span data-toggle="collapse" data-parent="#menu-group-1"
                                                href="#cat-lvl2-id-{{ forloop.parentloop.counter }}{{ forloop.counter }}" class="sign"><i class="fa fa-plus"></i></span>
                                            <span class="lbl lbl1">{{ mid_category.mid_category_name }}</span>
                                        </a>
                                        <ul class="children nav-child unstyled small collapse" id="cat-lvl2-id-{{ forloop.parentloop.counter }}{{ forloop.counter }}">
                                            {% for end_category in mid_category.add_end_category_set.all %}
                                            {% if end_category.show_end_menu %}
                                            <li class="item-111">
                                                <a class="" href="{% url 'filter_end_category' end_category.id %}">
                                                    <span class="sign"></span>
                                                    <span class="lbl lbl1">{{ end_category.end_category_name }}</span>
                                                </a>
                                            </li>
                                            {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                    
                </div>
                <div class="col-md-9">

                    <h3>All Products Under "Marbles"</h3>
                    <div class="product product-cat">

                        <div class="row">
                            {% if products %}
                            {% for i in products %}
                            <div class="col-md-4 item item-product-cat">
                                <div class="inner">
                                    <div class="thumb">
                                        <a href="{% url 'single_product' i.id %}">
                                        <div class="photo"
                                            style="background-image:url({{i.featured_photo.url}});">
                                        </div>
                                        </a>
                                        <div class=""></div>
                                    </div>
                                    <div class="text">
                                        <h3><a href="{% url 'single_product' i.id %}">{{i.product_name}}</a></h3>
                                        <h4>
                                            SQ.FT - <span style="color: green; font-weight: bold; font-size: 25px;"> {{i.current_price}} </span> Rs
                                        </h4>
                                        <div class="rating">
                                        </div>
                                        <p><a href="{% url 'single_product' i.id %}"><i class="fa fa-shopping-cart"></i> Add to
                                                Cart</a></p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            {% else %}
                                <p class="alert alert-danger">Sorry no record found</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'basic/footer.html' %}

    {% endblock %}

templates/search_product.html
{% extends 'basic/basic.html' %}

{% load static %}

{% block content %}

    {% include 'basic/top_navbar.html' %}

    {% include 'basic/center_navbar.html' %}

    {% include 'basic/main_navbar.html' %}

    <div class="page-banner" style="background-image: url({% static 'assets/uploads/banner_product_category.jpg' %})">
        <div class="inner">
            <h1>Category: Marbles </h1>
        </div>
    </div>

    <div class="page">
        <div class="container">
            <div class="row">
                <div class="col-md-3">

                    <h3>Categories</h3>
                    <div id="left" class="span3">
                        <ul id="menu-group-1" class="nav menu">
                            {% for top_category in top_categories %}
                            {% if top_category.show_top_menu %}
                            <li class="cat-level-1 deeper parent">
                                <a class="" href="{% url 'search_product_category' top_category.id %}">
                                    <span data-toggle="collapse" data-parent="#menu-group-1" href="#cat-lvl1-id-{{ forloop.counter }}"
                                        class="sign"><i class="fa fa-plus"></i></span>
                                    <span class="lbl">{{ top_category.top_category_name }}</span>
                                </a>
                                <ul class="children nav-child unstyled small collapse" id="cat-lvl1-id-{{ forloop.counter }}">
                                    {% for mid_category in top_category.add_mid_category_set.all %}
                                    {% if mid_category.show_mid_menu %}
                                    <li class="deeper parent">
                                        <a class="" href="{% url 'filter_mid_category' mid_category.id %}">
                                            <span data-toggle="collapse" data-parent="#menu-group-1"
                                                href="#cat-lvl2-id-{{ forloop.parentloop.counter }}{{ forloop.counter }}" class="sign"><i class="fa fa-plus"></i></span>
                                            <span class="lbl lbl1">{{ mid_category.mid_category_name }}</span>
                                        </a>
                                        <ul class="children nav-child unstyled small collapse" id="cat-lvl2-id-{{ forloop.parentloop.counter }}{{ forloop.counter }}">
                                            {% for end_category in mid_category.add_end_category_set.all %}
                                            {% if end_category.show_end_menu %}
                                            <li class="item-111">
                                                <a class="" href="{% url 'search_product_category' end_category.id %}">
                                                    <span class="sign"></span>
                                                    <span class="lbl lbl1">{{ end_category.end_category_name }}</span>
                                                </a>
                                            </li>
                                            {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                    
                </div>
                <div class="col-md-9">

                    <h3>All Products Under "Marbles"</h3>
                    <div class="product product-cat">

                        <div class="row">
                            {% if products %}
                            {% for i in products %}
                            <div class="col-md-4 item item-product-cat">
                                <div class="inner">
                                    <div class="thumb">
                                        <div class="photo"
                                            style="background-image:url({{i.featured_photo.url}});">
                                        </div>
                                        <div class=""></div>
                                    </div>
                                    <div class="text">
                                        <h3><a href="{% url 'single_product' i.id %}">{{i.product_name}}</a></h3>
                                        <h4>
                                            SQ.FT - <span style="color: green; font-weight: bold; font-size: 25px;"> {{i.current_price}} </span> Rs
                                        </h4>
                                        <div class="rating">
                                        </div>
                                        <p><a href="{% url 'single_product' i.id %}"><i class="fa fa-shopping-cart"></i> Add to
                                                Cart</a></p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            {% else %}
                                <p class="alert alert-danger">Sorry no record found</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'basic/footer.html' %}

    {% endblock %}